# Generated by Django 4.2.28 on 2026-02-09 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('driver', 'Driver'), ('viewer', 'Viewer')], default='viewer', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_ops_team', models.BooleanField(default=False)),
                ('is_deliveryq', models.BooleanField(default=False)),
                ('pia_access', models.BooleanField(default=False)),
                ('is_api_user', models.BooleanField(default=False)),
                ('token_never_expires', models.BooleanField(default=False)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_source', models.CharField(choices=[('local', 'Local Database'), ('pops', 'POPS API'), ('rider', 'Rider Account'), ('webhook', 'Webhook')], default='local', max_length=20)),
                ('tokens_revoked', models.BooleanField(default=False)),
                ('tokens_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RiderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rider_type', models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('3pl', '3PL'), ('hyperlocal', 'Hyperlocal')], default='bike', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rider', models.BooleanField(default=True)),
                ('pops_rider_id', models.IntegerField(blank=True, null=True)),
                ('synced_to_pops', models.BooleanField(default=False)),
                ('pops_sync_error', models.TextField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rider_accounts',
                'indexes': [models.Index(fields=['rider_id'], name='rider_accou_rider_i_181393_idx'), models.Index(fields=['is_active'], name='rider_accou_is_acti_f5cd51_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
                'indexes': [models.Index(fields=['user'], name='user_sessio_user_id_eb20aa_idx'), models.Index(fields=['expires_at'], name='user_sessio_expires_66ae96_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlackListedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, choices=[('logout', 'User Logout'), ('revoked', 'Admin Revocation'), ('security', 'Security Breach')], default='logout', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blacklisted_tokens',
                'indexes': [models.Index(fields=['user', 'token'], name='blacklisted_user_id_b388e5_idx'), models.Index(fields=['timestamp'], name='blacklisted_timesta_4fd334_idx')],
                'unique_together': {('token', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
    ]
