# Generated by Django 4.2.28 on 2026-02-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideraccount',
            name='dispatch_option',
            field=models.CharField(choices=[('printo-bike', 'Printo Bike'), ('milkround', 'Milkround Auto'), ('goods-auto', 'Goods Auto'), ('3PL', '3PL')], default='printo-bike', help_text='Type of delivery this rider handles (synced to POPS as tags)', max_length=50),
        ),
    ]
