# Generated by Django 4.2.27 on 2026-01-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_api_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_source',
            field=models.CharField(choices=[('local', 'Local Database'), ('pops', 'POPS API'), ('rider', 'Rider Account'), ('webhook', 'Webhook')], default='local', max_length=20),
        ),
    ]
