# Generated by Django 4.2.28 on 2026-02-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rideraccount_dispatch_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homebase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pops_homebase_id', models.IntegerField(blank=True, help_text='Homebase ID from POPS', null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('homebase_id', models.CharField(help_text='Homebase identifier code', max_length=100, unique=True)),
                ('aggregator_id', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum number of riders', null=True)),
                ('synced_from_pops', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homebase',
                'verbose_name_plural': 'Homebases',
                'db_table': 'homebases',
            },
        ),
        migrations.CreateModel(
            name='RiderHomebaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('pops_rider_id', models.IntegerField(blank=True, help_text='Rider record ID in POPS for this homebase', null=True)),
                ('synced_to_pops', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homebase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.homebase')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.rideraccount')),
            ],
            options={
                'verbose_name': 'Rider Homebase Assignment',
                'verbose_name_plural': 'Rider Homebase Assignments',
                'db_table': 'rider_homebase_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='homebase',
            index=models.Index(fields=['homebase_id'], name='homebases_homebas_f19500_idx'),
        ),
        migrations.AddIndex(
            model_name='homebase',
            index=models.Index(fields=['pops_homebase_id'], name='homebases_pops_ho_0b3b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='homebase',
            index=models.Index(fields=['is_active'], name='homebases_is_acti_23ae5c_idx'),
        ),
        migrations.AddField(
            model_name='rideraccount',
            name='homebases',
            field=models.ManyToManyField(related_name='assigned_riders', through='authentication.RiderHomebaseAssignment', to='authentication.homebase'),
        ),
        migrations.AddField(
            model_name='rideraccount',
            name='primary_homebase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_riders', to='authentication.homebase'),
        ),
        migrations.AddIndex(
            model_name='riderhomebaseassignment',
            index=models.Index(fields=['rider', 'is_active'], name='rider_homeb_rider_i_3c5435_idx'),
        ),
        migrations.AddIndex(
            model_name='riderhomebaseassignment',
            index=models.Index(fields=['homebase', 'is_active'], name='rider_homeb_homebas_c7f7b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riderhomebaseassignment',
            unique_together={('rider', 'homebase')},
        ),
    ]
