# Generated by Django 4.2.27 on 2026-01-29 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_webhook_auth_and_token_revocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, choices=[('logout', 'User Logout'), ('revoked', 'Admin Revocation'), ('security', 'Security Breach')], default='logout', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blacklisted_tokens',
                'indexes': [models.Index(fields=['user', 'token'], name='blacklisted_user_id_b388e5_idx'), models.Index(fields=['timestamp'], name='blacklisted_timesta_4fd334_idx')],
                'unique_together': {('token', 'user')},
            },
        ),
    ]
