# Generated by Django 4.2.28 on 2026-02-26 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('authentication', '0003_homebase_riderhomebaseassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideraccount',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='vehicles.vehicletype'),
        ),
        migrations.AlterField(
            model_name='rideraccount',
            name='rider_type',
            field=models.CharField(blank=True, choices=[('bike', 'Bike'), ('auto', 'Auto'), ('3pl', '3PL'), ('hyperlocal', 'Hyperlocal')], default='bike', help_text='Legacy field - use vehicle_type instead', max_length=50, null=True),
        ),
    ]
