# Generated by Django 4.2.30 on 2026-06-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_vehiclechangerequest_tidy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideraccount',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rideraccount',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
