# Generated by Django 4.2.30 on 2026-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rideraccount_archived_at_rideraccount_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(default='rider_login', max_length=50)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'expires_at'], name='otp_challen_phone_3f76b3_idx')],
            },
        ),
    ]
