# Generated by Django 4.2.30 on 2026-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_otpchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='plaintext_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
