# Generated by Django 4.2.27 on 2026-01-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=50)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('total_distance', models.FloatField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('fuel_consumed', models.FloatField(default=0)),
                ('fuel_cost', models.FloatField(default=0)),
                ('average_speed', models.FloatField(default=0)),
                ('shipments_completed', models.IntegerField(default=0)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'route_sessions',
            },
        ),
        migrations.CreateModel(
            name='RouteTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('gps', 'GPS Point'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], default='gps', max_length=50)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_efficiency', models.FloatField(default=15.0)),
                ('fuel_price', models.FloatField(default=1.5)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='routes.routesession')),
            ],
            options={
                'db_table': 'route_tracking',
            },
        ),
        migrations.AddIndex(
            model_name='routesession',
            index=models.Index(fields=['employee_id'], name='route_sessi_employe_3f278e_idx'),
        ),
        migrations.AddIndex(
            model_name='routesession',
            index=models.Index(fields=['start_time'], name='route_sessi_start_t_ad9d26_idx'),
        ),
        migrations.AddIndex(
            model_name='routesession',
            index=models.Index(fields=['status'], name='route_sessi_status_598254_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['session'], name='route_track_session_059453_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['employee_id'], name='route_track_employe_e61ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['date'], name='route_track_date_799f54_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['timestamp'], name='route_track_timesta_accf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['employee_id', 'date'], name='route_track_employe_f17c96_idx'),
        ),
    ]
