# Generated by Django 4.2.28 on 2026-02-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fuel_efficiency', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='car', max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], default='petrol', max_length=50)),
                ('co2_emissions', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_types',
            },
        ),
        migrations.CreateModel(
            name='FuelSetting',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], default='petrol', max_length=50)),
                ('price_per_liter', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fuel_settings',
                'indexes': [models.Index(fields=['fuel_type', 'is_active'], name='fuel_settin_fuel_ty_513db9_idx')],
            },
        ),
    ]
