# Generated by Django 4.2.27 on 2026-01-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=50)),
                ('customer_name', models.TextField()),
                ('customer_mobile', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField()),
                ('delivery_time', models.DateTimeField()),
                ('route_name', models.TextField()),
                ('employee_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Picked Up', 'Picked Up'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Assigned', max_length=50)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(default=0)),
                ('dimensions', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('stop_latitude', models.FloatField(blank=True, null=True)),
                ('stop_longitude', models.FloatField(blank=True, null=True)),
                ('km_travelled', models.FloatField(default=0)),
                ('synced_to_external', models.BooleanField(default=False)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('needs_sync', 'Needs Sync')], default='pending', max_length=20)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('signature_url', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('acknowledgment_captured_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_captured_by', models.CharField(blank=True, max_length=255, null=True)),
                ('pops_order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('pops_shipment_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='acknowledgment', serialize=False, to='shipments.shipment')),
                ('signature_url', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('acknowledgment_captured_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledgment_captured_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'acknowledgments',
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['employee_id'], name='shipments_employe_1f5ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_created_b63910_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['synced_to_external', 'sync_status'], name='shipments_synced__098cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'type', 'route_name', 'created_at'], name='shipments_status_cde5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['latitude', 'longitude'], name='shipments_latitud_5e8282_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['pops_order_id'], name='shipments_pops_or_060b79_idx'),
        ),
    ]
