# Generated by Django 4.2.28 on 2026-02-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=50)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('total_distance', models.FloatField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('fuel_consumed', models.FloatField(default=0)),
                ('fuel_cost', models.FloatField(default=0)),
                ('average_speed', models.FloatField(default=0)),
                ('shipments_completed', models.IntegerField(default=0)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'route_sessions',
            },
        ),
        migrations.CreateModel(
            name='RouteTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('gps', 'GPS Point'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], default='gps', max_length=50)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_efficiency', models.FloatField(default=15.0)),
                ('fuel_price', models.FloatField(default=1.5)),
            ],
            options={
                'db_table': 'route_tracking',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=50, null=True)),
                ('customer_name', models.TextField()),
                ('customer_mobile', models.TextField()),
                ('address', models.JSONField(blank=True, help_text='Delivery address as JSON object', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField()),
                ('delivery_time', models.DateTimeField()),
                ('route_name', models.TextField()),
                ('employee_id', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('Assigned', 'Assigned'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Picked Up', 'Picked Up'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('pickup_address', models.JSONField(blank=True, help_text='Pickup address as JSON object (from clickpost logic)', null=True)),
                ('weight', models.FloatField(default=0)),
                ('package_boxes', models.JSONField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('stop_latitude', models.FloatField(blank=True, null=True)),
                ('stop_longitude', models.FloatField(blank=True, null=True)),
                ('km_travelled', models.FloatField(default=0)),
                ('synced_to_external', models.BooleanField(default=False)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('needs_sync', 'Needs Sync')], default='pending', max_length=20)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('signature_url', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('acknowledgment_captured_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_captured_by', models.CharField(blank=True, max_length=255, null=True)),
                ('pops_order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('pops_shipment_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('api_source', models.CharField(blank=True, help_text='Source of the API call that created this shipment (e.g., printo_api_key_2024, external_system_key_1)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='acknowledgment', serialize=False, to='shipments.shipment')),
                ('signature_url', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('acknowledgment_captured_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledgment_captured_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'acknowledgments',
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['employee_id'], name='shipments_employe_1f5ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_created_b63910_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['synced_to_external', 'sync_status'], name='shipments_synced__098cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'type', 'route_name', 'created_at'], name='shipments_status_cde5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['latitude', 'longitude'], name='shipments_latitud_5e8282_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['pops_order_id'], name='shipments_pops_or_060b79_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['api_source'], name='shipments_api_sou_c77b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['api_source', 'created_at'], name='shipments_api_sou_a30e93_idx'),
        ),
        migrations.AddField(
            model_name='routetracking',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='shipments.routesession'),
        ),
        migrations.AddIndex(
            model_name='routesession',
            index=models.Index(fields=['employee_id'], name='route_sessi_employe_3f278e_idx'),
        ),
        migrations.AddIndex(
            model_name='routesession',
            index=models.Index(fields=['start_time'], name='route_sessi_start_t_ad9d26_idx'),
        ),
        migrations.AddIndex(
            model_name='routesession',
            index=models.Index(fields=['status'], name='route_sessi_status_598254_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['session'], name='route_track_session_059453_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['employee_id'], name='route_track_employe_e61ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['date'], name='route_track_date_799f54_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['timestamp'], name='route_track_timesta_accf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['employee_id', 'date'], name='route_track_employe_f17c96_idx'),
        ),
    ]
