# Generated by Django 4.2.28 on 2026-02-18 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_homebase_riderhomebaseassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgmentSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(help_text='Region identifier (city, state, or custom name)', max_length=100, unique=True)),
                ('region_display_name', models.CharField(help_text='Display name for the region', max_length=255)),
                ('signature_required', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional'), ('either', 'Either (one of signature or photo required)')], default='optional', help_text='Signature requirement: mandatory, optional, or either', max_length=20)),
                ('photo_required', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional'), ('either', 'Either (one of signature or photo required)')], default='optional', help_text='Photo requirement: mandatory, optional, or either', max_length=20)),
                ('require_pdf', models.BooleanField(default=False, help_text='Whether to require PDF document for signing')),
                ('pdf_template_url', models.TextField(blank=True, help_text='URL to PDF template for this region', null=True)),
                ('allow_skip_acknowledgment', models.BooleanField(default=False, help_text='Allow riders to skip acknowledgment in exceptional cases')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acknowledgment Setting',
                'verbose_name_plural': 'Acknowledgment Settings',
                'db_table': 'acknowledgment_settings',
                'ordering': ['region'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('pickup', 'Pickup'), ('delivery', 'Delivery'), ('assignment', 'Assignment'), ('route_start', 'Route Start'), ('route_end', 'Route End'), ('acknowledgment', 'Acknowledgment'), ('sync', 'Sync Event'), ('error', 'Error')], max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional event data', null=True)),
                ('triggered_by', models.CharField(blank=True, help_text='User or system that triggered the event', max_length=255, null=True)),
                ('synced_to_pops', models.BooleanField(default=False)),
                ('sync_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteSession',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=50)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('total_distance', models.FloatField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('fuel_consumed', models.FloatField(default=0)),
                ('fuel_cost', models.FloatField(default=0)),
                ('average_speed', models.FloatField(default=0)),
                ('shipments_completed', models.IntegerField(default=0)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'route_sessions',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('delivery', 'Delivery'), ('pickup', 'Pickup')], max_length=50, null=True)),
                ('customer_name', models.TextField()),
                ('customer_mobile', models.TextField()),
                ('address', models.JSONField(blank=True, help_text='Delivery address as JSON object', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField()),
                ('delivery_time', models.DateTimeField()),
                ('route_name', models.TextField()),
                ('employee_id', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('Assigned', 'Assigned'), ('Collected', 'Collected'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Picked Up', 'Picked Up'), ('Skipped', 'Skipped'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('pickup_address', models.JSONField(blank=True, help_text='Pickup address as JSON object (from clickpost logic)', null=True)),
                ('weight', models.FloatField(default=0)),
                ('package_boxes', models.JSONField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('stop_latitude', models.FloatField(blank=True, null=True)),
                ('stop_longitude', models.FloatField(blank=True, null=True)),
                ('km_travelled', models.FloatField(default=0)),
                ('synced_to_external', models.BooleanField(default=False)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('needs_sync', 'Needs Sync')], default='pending', max_length=20)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('signature_url', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True, help_text='URL to PDF document for signing', null=True)),
                ('signed_pdf_url', models.TextField(blank=True, help_text='URL to signed PDF after recipient signs', null=True)),
                ('acknowledgment_captured_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_captured_by', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, help_text='Region/city for acknowledgment settings', max_length=100, null=True)),
                ('homebase_slot', models.JSONField(blank=True, help_text='Homebase slot information from POPS', null=True)),
                ('homebase_transaction_duration', models.IntegerField(default=300, help_text='Transaction duration at homebase in seconds', null=True)),
                ('pops_order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('pops_shipment_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('api_source', models.CharField(blank=True, help_text='Source of the API call that created this shipment (e.g., printo_api_key_2024, external_system_key_1)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homebase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='authentication.homebase')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='acknowledgment', serialize=False, to='shipments.shipment')),
                ('signature_url', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('acknowledgment_captured_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledgment_captured_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'acknowledgments',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('boundaries', models.JSONField(blank=True, help_text='Array of [lat, lng] coordinates defining zone polygon', null=True)),
                ('center_latitude', models.FloatField(blank=True, null=True)),
                ('center_longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('max_shipments', models.IntegerField(default=50, help_text='Maximum shipments per zone per day')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_riders', models.ManyToManyField(blank=True, related_name='zones', to='authentication.rideraccount')),
            ],
            options={
                'db_table': 'zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('gps', 'GPS Point'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], default='gps', max_length=50)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_efficiency', models.FloatField(default=15.0)),
                ('fuel_price', models.FloatField(default=1.5)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='shipments.routesession')),
            ],
            options={
                'db_table': 'route_tracking',
            },
        ),
        migrations.AddIndex(
            model_name='routesession',
            index=models.Index(fields=['employee_id'], name='route_sessi_employe_3f278e_idx'),
        ),
        migrations.AddIndex(
            model_name='routesession',
            index=models.Index(fields=['start_time'], name='route_sessi_start_t_ad9d26_idx'),
        ),
        migrations.AddIndex(
            model_name='routesession',
            index=models.Index(fields=['status'], name='route_sessi_status_598254_idx'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='acknowledgmentsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledgment_settings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['city', 'is_active'], name='zones_city_b0240d_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['is_active'], name='zones_is_acti_eda58f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['employee_id'], name='shipments_employe_1f5ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_created_b63910_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['synced_to_external', 'sync_status'], name='shipments_synced__098cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', 'type', 'route_name', 'created_at'], name='shipments_status_cde5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['latitude', 'longitude'], name='shipments_latitud_5e8282_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['pops_order_id'], name='shipments_pops_or_060b79_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['api_source'], name='shipments_api_sou_c77b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['api_source', 'created_at'], name='shipments_api_sou_a30e93_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['session'], name='route_track_session_059453_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['employee_id'], name='route_track_employe_e61ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['date'], name='route_track_date_799f54_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['timestamp'], name='route_track_timesta_accf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='routetracking',
            index=models.Index(fields=['employee_id', 'date'], name='route_track_employe_f17c96_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['shipment', '-created_at'], name='order_event_shipmen_ddf1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['event_type', '-created_at'], name='order_event_event_t_3cfcce_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['synced_to_pops', 'sync_attempted_at'], name='order_event_synced__3900a1_idx'),
        ),
        migrations.AddIndex(
            model_name='acknowledgmentsettings',
            index=models.Index(fields=['region', 'is_active'], name='acknowledgm_region_a5e37e_idx'),
        ),
        migrations.AddIndex(
            model_name='acknowledgmentsettings',
            index=models.Index(fields=['is_active'], name='acknowledgm_is_acti_fb3719_idx'),
        ),
    ]
