# Generated by Django 4.2.28 on 2026-02-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('boundaries', models.JSONField(blank=True, help_text='Array of [lat, lng] coordinates defining zone polygon', null=True)),
                ('center_latitude', models.FloatField(blank=True, null=True)),
                ('center_longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('max_shipments', models.IntegerField(default=50, help_text='Maximum shipments per zone per day')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_riders', models.ManyToManyField(blank=True, related_name='zones', to='authentication.rideraccount')),
            ],
            options={
                'db_table': 'zones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='zones_city_b0240d_idx'), models.Index(fields=['is_active'], name='zones_is_acti_eda58f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('pickup', 'Pickup'), ('delivery', 'Delivery'), ('assignment', 'Assignment'), ('route_start', 'Route Start'), ('route_end', 'Route End'), ('acknowledgment', 'Acknowledgment'), ('sync', 'Sync Event'), ('error', 'Error')], max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional event data', null=True)),
                ('triggered_by', models.CharField(blank=True, help_text='User or system that triggered the event', max_length=255, null=True)),
                ('synced_to_pops', models.BooleanField(default=False)),
                ('sync_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipments.shipment')),
            ],
            options={
                'db_table': 'order_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shipment', '-created_at'], name='order_event_shipmen_ddf1e5_idx'), models.Index(fields=['event_type', '-created_at'], name='order_event_event_t_3cfcce_idx'), models.Index(fields=['synced_to_pops', 'sync_attempted_at'], name='order_event_synced__3900a1_idx')],
            },
        ),
    ]
