# Generated by Django 4.2.30 on 2026-06-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_routesession_mileage_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='hub_job_entries',
            field=models.JSONField(blank=True, help_text='Paired hubjob_id + bill_code entries from PIA (list of objects)', null=True),
        ),
    ]
