# Generated by Django 4.2.28 on 2026-02-10 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0002_zone_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='pdf_url',
            field=models.TextField(blank=True, help_text='URL to PDF document for signing', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='region',
            field=models.CharField(blank=True, help_text='Region/city for acknowledgment settings', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='signed_pdf_url',
            field=models.TextField(blank=True, help_text='URL to signed PDF after recipient signs', null=True),
        ),
        migrations.CreateModel(
            name='AcknowledgmentSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(help_text='Region identifier (city, state, or custom name)', max_length=100, unique=True)),
                ('region_display_name', models.CharField(help_text='Display name for the region', max_length=255)),
                ('signature_required', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional'), ('either', 'Either (one of signature or photo required)')], default='optional', help_text='Signature requirement: mandatory, optional, or either', max_length=20)),
                ('photo_required', models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional'), ('either', 'Either (one of signature or photo required)')], default='optional', help_text='Photo requirement: mandatory, optional, or either', max_length=20)),
                ('require_pdf', models.BooleanField(default=False, help_text='Whether to require PDF document for signing')),
                ('pdf_template_url', models.TextField(blank=True, help_text='URL to PDF template for this region', null=True)),
                ('allow_skip_acknowledgment', models.BooleanField(default=False, help_text='Allow riders to skip acknowledgment in exceptional cases')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledgment_settings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acknowledgment Setting',
                'verbose_name_plural': 'Acknowledgment Settings',
                'db_table': 'acknowledgment_settings',
                'ordering': ['region'],
                'indexes': [models.Index(fields=['region', 'is_active'], name='acknowledgm_region_a5e37e_idx'), models.Index(fields=['is_active'], name='acknowledgm_is_acti_fb3719_idx')],
            },
        ),
    ]
