# Generated by Django 4.2.30 on 2026-06-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_hub_job_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlapIgnore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('wave', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'overlap_ignores',
                'indexes': [models.Index(fields=['date', 'wave'], name='overlap_ign_date_8518fe_idx')],
                'unique_together': {('date', 'wave', 'pincode')},
            },
        ),
    ]
