# Generated by Django 4.2.28 on 2026-02-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_add_api_source_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shipment',
            new_name='shipments_api_sou_c77b7d_idx',
            old_name='shipments_shipment_api_source_idx',
        ),
        migrations.RenameIndex(
            model_name='shipment',
            new_name='shipments_api_sou_a30e93_idx',
            old_name='shipments_shipment_api_source_created_at_idx',
        ),
    ]
