# Generated by Django 4.2.28 on 2026-02-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_pdf_url_shipment_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesession',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routesession',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routesession',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
