# Generated by Django 4.2.30 on 2026-06-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_overlapignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='dispatch_sequence',
            field=models.IntegerField(blank=True, help_text='Locked stop order set by ops dispatch; null = not dispatched', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, help_text="When ops dispatched/locked this shipment's route", null=True),
        ),
    ]
