# Generated by Django 4.2.28 on 2026-02-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_homebase_riderhomebaseassignment_and_more'),
        ('shipments', '0004_routesession_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='homebase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='authentication.homebase'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='homebase_slot',
            field=models.JSONField(blank=True, help_text='Homebase slot information from POPS', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='homebase_transaction_duration',
            field=models.IntegerField(default=300, help_text='Transaction duration at homebase in seconds', null=True),
        ),
    ]
