# Generated by Django 4.2.28 on 2026-02-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_homebase_shipment_homebase_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('Assigned', 'Assigned'), ('Collected', 'Collected'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Picked Up', 'Picked Up'), ('Skipped', 'Skipped'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
